### ISSUE TITLE
License

### ISSUE THREAD

**Issue by retina-cmV0aW5hCg** [gishi523/semi-global-matching#3]
Hi @gishi523,

thanks for your code!
I would really like to use it for R&D in a company context. 
However, to do so, I need to clear it for a certain license preferably MIT or BSD3.
Could you please add (such) a license information?

Thanks!

**Comment by gishi523** [comment]
Hi, @hays-retina 

This is MIT license.
I added LICENSE file.

Regards,

**Comment by retina-cmV0aW5hCg** [comment]
Thanks!
